services:
  app:
    container_name: rebble-asr
    build: .
    ports:
      - "9039:9039"
    restart: always
    environment:
      - ASR_API_KEY=${ASR_API_KEY}
      - ASR_API_PROVIDER=vosk # or groq or elevenlabs
      - PORT=9039